### ISSUE TITLE
!s crash the bot

### ISSUE THREAD

**Issue by 123Remo** [sharkbound/PythonTwitchBotFramework#24]
Hello! 

I got this working in raspberry pi but when i use default !s command in any other than admin account it crashes whole bot. So anyone can crash it.  Below the errors it gets. Same happens in windows machine.

Traceback (most recent call last):
  File "test.py", line 46, in <module>
    AddstarBot().run()
  File "/home/pi/.local/lib/python3.7/site-packages/twitchbot/bots/basebot.py", line 299, in run
    get_event_loop().run_until_complete(self.mainloop())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/pi/.local/lib/python3.7/site-packages/twitchbot/bots/basebot.py", line 326, in mainloop
    msg = Message(raw_msg, irc=self.irc, bot=self)
  File "/home/pi/.local/lib/python3.7/site-packages/twitchbot/message.py", line 40, in __init__
    self._parse()
  File "/home/pi/.local/lib/python3.7/site-packages/twitchbot/message.py", line 83, in _parse
    or self._parse_notice()
  File "/home/pi/.local/lib/python3.7/site-packages/twitchbot/message.py", line 186, in _parse_notice
    self.channel = channels[m['channel']]

To my use i only need info when someone donate bits , follows and subs channel. Is this right tool to use and does it get "real" bits donated or can viewers do fake donations.

Cheers!

**Comment by sharkbound** [comment]
> Is this right tool to use and does it get "real" bits donated or can viewers do fake donations
the bot checks the irc message tags/metadata, which to my knowledge cannot be faked

i am also working on a pubsub client built in as well, but its not in the current release

as for the crash, it seems like a key error, which is solved easy enough

**Comment by 123Remo** [comment]
Ok nice to hear! Ill wait fix 👍

**Comment by sharkbound** [comment]
i am trying to do a fix, having git related issues with trying to apply it to 2 branches.
will update when its done

**Comment by sharkbound** [comment]
finishing the fix now, i had to guess at the issue due you how vague async errors are at times, so i will keep this open until its pushed and you can test it in your environment

**Comment by sharkbound** [comment]
i pushed a potential fix in pypi version 1.13.0

**Comment by 123Remo** [comment]
Ok i did pip3 uninstall and then installed 1.13.0 version now when i run it ill get error.

Traceback (most recent call last):
  File "test.py", line 5, in <module>
    from twitchbot.bots import BaseBot
  File "/home/pi/.local/lib/python3.7/site-packages/twitchbot/__init__.py", line 15, in <module>
    from .bots import *
  File "/home/pi/.local/lib/python3.7/site-packages/twitchbot/bots/__init__.py", line 1, in <module>
    from .basebot import *
  File "/home/pi/.local/lib/python3.7/site-packages/twitchbot/bots/basebot.py", line 31, in <module>
    from ..pubsub import PubSubClient
  File "/home/pi/.local/lib/python3.7/site-packages/twitchbot/pubsub/__init__.py", line 1, in <module>
    from .client import *
  File "/home/pi/.local/lib/python3.7/site-packages/twitchbot/pubsub/client.py", line 14, in <module>
    from .models import PubSubData
  File "/home/pi/.local/lib/python3.7/site-packages/twitchbot/pubsub/models.py", line 5, in <module>
    from functools import cached_property
ImportError: cannot import name 'cached_property' from 'functools' (/usr/lib/python3.7/functools.py)

**Comment by 123Remo** [comment]
Ok looks like functools is not in Python 3.7 so iam upgrading to 3.8 right now

**Comment by 123Remo** [comment]
_Ok got it running now and !s dont crash bot anymore. However some messages are prompted when i start the bot._

Starting bot...
/usr/local/lib/python3.8/site-packages/aiohttp-4.0.0a1-py3.8-linux-armv7l.egg/aiohttp/client.py:977: RuntimeWarning: coroutine 'noop' was never awaited
  self._resp.release()
RuntimeWarning: Enable tracemalloc to get the object allocation `traceback

_And after some time pass messages below appear but bot will continue running._

Task exception was never retrieved
future: <Task finished name='Task-17' coro=<PubSubClient._processor_loop() done, defined at /usr/local/lib/python3.8/site-packages/PythonTwitchBotFramework-1.13.0-py3.8.egg/twitchbot/pubsub/client.py:112> exception=ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), no reason')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/websockets-8.1-py3.8-linux-armv7l.egg/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/usr/local/lib/python3.8/site-packages/websockets-8.1-py3.8-linux-armv7l.egg/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/usr/local/lib/python3.8/site-packages/websockets-8.1-py3.8-linux-armv7l.egg/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/usr/local/lib/python3.8/site-packages/websockets-8.1-py3.8-linux-armv7l.egg/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/usr/local/lib/python3.8/site-packages/websockets-8.1-py3.8-linux-armv7l.egg/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/local/lib/python3.8/asyncio/streams.py", line 738, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/PythonTwitchBotFramework-1.13.0-py3.8.egg/twitchbot/pubsub/client.py", line 116, in _processor_loop
    await self._read_and_handle()
  File "/usr/local/lib/python3.8/site-packages/PythonTwitchBotFramework-1.13.0-py3.8.egg/twitchbot/pubsub/client.py", line 125, in _read_and_handle
    raw_resp = await self.read(timeout=10)
  File "/usr/local/lib/python3.8/site-packages/PythonTwitchBotFramework-1.13.0-py3.8.egg/twitchbot/pubsub/client.py", line 94, in read
    data = await asyncio.wait_for(self.socket.recv(), timeout=timeout)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.8/site-packages/websockets-8.1-py3.8-linux-armv7l.egg/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/usr/local/lib/python3.8/site-packages/websockets-8.1-py3.8-linux-armv7l.egg/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

**Comment by sharkbound** [comment]
those both seem related to PUBSUB client stuff, it should not affect bot usage, unless you are using the pubsub client the bot includes

**Comment by sharkbound** [comment]
i will look into the pubsub errors though, pubsub client that comes with the bot is still being worked on

**Comment by 123Remo** [comment]
Well its working great! It might be first time someone use your bot on raspberry pi + diy bird feeder? :) If you want to whisper me at twitch so i add you as VIP to use it free. My stream with feeder is here  [https://www.twitch.tv/wildlifestreamer2](url)

Cheers!

**Comment by sharkbound** [comment]
i will be pushing a update to fix the connection errors at starts (and few mins after), found out its when pubsub is not used, so twitch (the socket) closes the connection

**Comment by sharkbound** [comment]
pypi version 1.13.1 should have fixed the connection issues on startup, if you care about it
